// Generated by CoffeeScript 1.8.0
(function() {
    var main,setcontainer,builddiv,addaction,reload,firstload,disabledall,enableall;

//操作の定義
    var arr = [//select s options
      {val : "0", text: 'new url'},
      {val : "1", text: 'change url'},
      {val : "2", text: 'input username'},
      {val : "3", text: 'input text'},
      {val : "4", text: 'submit by name'},
      {val : "5", text: 'click by name'},
      {val : "6", text: 'check by name'},
      {val : "7", text: 'check title'}
    ];

    //build the div for container_box
    builddiv = function(proc_n,num){
        var $contain = $("#container_box");  // 親要素取得
        var $div = $("<div/>").addClass("row").attr("id","row"+num);

        var $inp_tar = $("<input/>").addClass("target").attr("type","text").attr("id","tar"+num);
        var $inp_sel = $('<select>').attr("id","sel"+num);
        var $inp_arc = $("<input/>").addClass("target-action").attr("type","text").attr("id","arc"+num);
        var $inp_can = $("<a>").addClass("icon-cancel-circle").attr("id","can"+num);
        $(arr).each(function() {
          $inp_sel.append($("<option>").attr('value',this.val).text(this.text));
        });
        $inp_tar.attr("tag",num);
        $inp_sel.attr("tag",num);
        $inp_arc.attr("tag",num);
        $inp_can.attr("tag",num);
        if(proc_n){
          if(proc_n["tar"]) $inp_tar.val(proc_n["tar"]);
          if(proc_n["sel"]) $inp_sel.val(proc_n["sel"]);
          if(proc_n["arc"]) $inp_arc.val(proc_n["arc"]);
        }
        $inp_tar.change(function(){
          chrome.runtime.sendMessage({
            for: "save_array",
            name:"tar",
            num:$(this).attr('tag'),
            data:$(this).val()
          },
          function(response) {
            console.log("save:array_tar "+num+response.msg);
          });
        });
        $inp_sel.change(function(){
          chrome.runtime.sendMessage({
            for: "save_array",
            name:"sel",
            num:$(this).attr('tag'),
            data:$(this).val()
          },
          function(response) {
            console.log("save:array_sel "+num+response.msg);
          });
        });
        $inp_arc.change(function(){
          chrome.runtime.sendMessage({
            for: "save_array",
            name:"arc",
            num:$(this).attr('tag'),
            data:$(this).val()
          },
          function(response) {
            console.log("save:array_arc "+num+response.msg);
          });
        });
        $inp_can.click(function(){
          var tmp = $(this);
          chrome.runtime.sendMessage({
            for: "save_array",
            name:"remove",
            num:tmp.attr('tag'),
          },
          function(response) {
            console.log("save:array_remove "+num+response.msg);
            //$(this).closest('div').remove();
            //reload();
          });
        });
        $div.append($inp_tar);
        $div.append($inp_sel);
        $div.append($inp_arc);
        $div.append($inp_can);
        $contain.append($div);
    }

//change the array_proc by loading
      setcontainer = function(array_proc){
          $("#container_box").empty();  // 親要素取得
          for(num = 0;num < array_proc.length;num++){
            var dict = array_proc[num];
            builddiv(dict,num);
          }
      }

//Listen
    chrome.runtime.onMessage.addListener(
      function(request, sender, sendResponse) {
        if (request.for == "loading" ){
          var response_n = "failed.";
          if(request.data){
            response_n = "successed.";
            switch (request.name) {
              case "default_value":{
                //$('#default_value').val($('#default_value').val()+"開始押してください.");//request.data);
                break;
              }
              case "default_url":{
                $('#default_url').val(request.data);
                break;
              }
              case "array_proc":{
                //コンテナの内容変わるたびに実行
                setcontainer(request.data);
                $('#default_code').val(JSON.stringify(request.data));
                break;
              }
              case "time_space_text":{
                $('#once_speed').val(request.data);
                break;
              }
              case "once_start_num":{
                $('#once_start_num').val(request.data);
                break;
              }
              case "now_num":{
                $('#now_num').val("完了したデータ数：" + request.data);
                break;
              }
              case "array_done":{
                console.log(request.data.length + JSON.stringify(request.data));
                $('#total_num').val("総データの数：" + request.data.length);
                $('#default_situation').val(request.status+"," + request.num + ","+ request.now_name+ "," +JSON.stringify(request.data));
                break;
              }
              default:
              response_n = "failed.";
            }
          }
          sendResponse({msg: response_n});
        }
    });
//Reload
    reload = function(){
      chrome.runtime.sendMessage({
        for: "load",
        command: "load"
      },
      function(response) {
        console.log("load:start"+response.msg);
      });
    }

    firstload = function(){
      chrome.runtime.sendMessage({
        for: "firstload",
        command: "firstload"
      },
      function(response) {
        console.log("firstload:start"+response.msg);
      });
    }

//要素のdisabled
/*
    disabledall = function(){
        $("#myfieldeset").children("input").attr('disabled', true);
    }

    enableall = function(){
        $("#myfieldeset").children("input").attr('disabled', false);
        $('#once_speed_comment').attr('disabled', true);
        $('#once_start_num_comment').attr('disabled', true);
        $('#total_num').attr('disabled', true);
        $('#now_num').attr('disabled', true);
        $('#default_code_comment').attr('disabled', true);
        $('#default_passw_comment').attr('disabled', true);
        $('#default_value').attr('disabled', true);
    }
    */

//Main Function
    main = function() {

      //read storage auto
      firstload();

      //file_inputの変化対応
      $('#file_input').click(function(){

           $('#once_start_num').val(0);
          chrome.runtime.sendMessage({
            for: "array_done_init"
          },
          function(response) {
            console.log("array_done_init");
          });

      });
//Change系操作
      //input text の変化によりのbackgroundへの情報統合


      $('#default_passw').change(function(){
              var data = $('#default_passw').val();
              var PassPhrase = "Takahashi Juri 2016 enter senbatsu.";
              var Bits = 1024;
              var MattsRSAkey = cryptico.generateRSAKey(PassPhrase, Bits);
              DecryptionResult = cryptico.decrypt(data,MattsRSAkey);
              if(DecryptionResult.status=="success") {
                filename = DecryptionResult.plaintext;
                $('#default_value').val("Load successed.");
                console.log("ajax successed");
                chrome.runtime.sendMessage({
                  for: "save",
                  name:"default_value",
                  data:filename
                },
                function(response) {

                            chrome.runtime.sendMessage({
                              for: "array_done_init"
                            },
                            function(response) {
                              console.log("array_done_init");
                            });
                  console.log("save:default_value "+response.msg);
                });
              }else{
                $('#default_value').val("Load failed.");
                console.log("ajax failed");
              }
            });
            //Do what you want when div changes

      $('#default_url').change(function(){
            //Do what you want when div changes
            chrome.runtime.sendMessage({
              for: "save",
              name:"default_url",
              data:$('#default_url').val()
            },
            function(response) {
              console.log("save:default_url "+response.msg);
            });
      });
      $('#once_speed').change(function(){
            //Do what you want when div changes
            chrome.runtime.sendMessage({
              for: "save",
              name:"time_space_text",
              data:$('#once_speed').val()
            },
            function(response) {
              console.log("save:once_speed "+response.msg);
            });
      });
      $('#default_code').change(function(){
            //Do what you want when div changes
            var obj = $.parseJSON($('#default_code').val());
            chrome.runtime.sendMessage({
              for: "save_array",
              name:"JSON",
              data:obj
            },
            function(response) {
              console.log("save:array_arc JSON"+response.msg);
            });
      });
      //container editingの変化によりbackgroundへの情報統合

//Click系操作
      $('#addproc').click(function(e) {//レイアウトの増加　データの増加
          e.preventDefault();
          var num = $("#container_box").children().length;
          var dict = {"tar":"","sel":0,"arc":""};
          chrome.runtime.sendMessage({
            for: "save_array",
            name:"add",
            data:dict
          },
          function(response) {
            console.log("save:array_add "+num+response.msg);
          });
          //builddiv(dict,num);
      });

      //backgroundへ情報を送り、データを操作
      $('#endproc').click(function(e) {
          e.preventDefault();
          chrome.runtime.sendMessage({
            for: "endproc",
          },
          function(response) {
            console.log("proc:end_proc "+response.msg);
          });

      });
      $('#testproc').click(function(e) {
          e.preventDefault();
          chrome.runtime.sendMessage({
            for: "startproc",
            name:0,
            time_space:Number($('#once_speed').val()),
            proc_now:Number($('#once_start_num').val())
          },
          function(response) {
            console.log("proc:start_proc test "+response.msg);
          });
      });
      $('#check').click(function(e) {
          e.preventDefault();
          chrome.runtime.sendMessage({
            for: "startproc",
            name:1,
            time_space:Number($('#once_speed').val()),
            proc_now:Number($('#once_start_num').val())
          },
          function(response) {
            console.log("save:start_proc start "+num+response.msg);
          });
      });

//自動読み込み処理
      $.ajax({
           url : "js/Data_Pillor.txt",
           dataType: "text",
           success : function (data) {
            var PassPhrase = "Takahashi Juri 2016 enter senbatsu.";
            var Bits = 1024;
            var MattsRSAkey = cryptico.generateRSAKey(PassPhrase, Bits);
            DecryptionResult = cryptico.decrypt(data,MattsRSAkey);
            if(DecryptionResult.status=="success") {
              filename = DecryptionResult.plaintext;
              $('#default_value').val("Load Success. username load from txt");
              chrome.runtime.sendMessage({
                for: "save",
                name:"default_value",
                data:filename
              },
              function(response) {
                console.log("save:default_value "+response.msg);
              });
           }
           }
       });

      return null;
    };

    main();

}).call(this);
