// Generated by CoffeeScript 1.8.0
(function() {

  chrome.extension.onRequest.addListener(
    function(request, sender, sendResponse) {
      if(request.for == "proc_action"){
        switch (request.sel) {
          case "2":{
            var x = document.getElementsByName(request.tar);
            var i;
            for (i = 0; i < x.length; i++) {
              if (x[i].type == "text") {
                x[i].value = request.username;
              }
            }
            console.log(request.tar+" "+request.sel+" "+request.username);
            sendResponse({
              msg:"input username successed."+request.username+" "+request.run_now,
              run_now: request.run_now,
              hantei: "disabled"
            });

            break;
          }
          case "3":{
            var x = document.getElementsByName(request.tar);
            var i;
            for (i = 0; i < x.length; i++) {
                x[i].value = request.arc;
            }
            console.log(request.tar+" "+request.sel+" "+request.arc);

            sendResponse({
              msg:"input text successed."+request.arc+" "+request.run_now,
              run_now: request.run_now,
              hantei: "disabled"
            });
            break;
          }
          case "4":{
            console.log(request.tar+" "+request.sel);

            sendResponse({
              msg:"submit successed."+" "+request.run_now,
              run_now: request.run_now,
              hantei: "disabled"
            });
            document.getElementsByName(request.tar)[0].submit();
            break;
          }
          case "5":{
            console.log(request.tar+" "+request.sel);
            sendResponse({
              msg:"click successed."+" "+request.run_now,
              run_now: request.run_now,
              hantei: "disabled"
            });
            document.getElementsByName(request.tar)[0].click();
            break;
          }
          case "6":{
            var x = document.getElementsByName(request.tar)[0];
            console.log(request.tar+" "+ x +" "+request.arc);
            var res = "false";
            if(x.content==request.arc) res = "true";

            sendResponse({
              msg:"check the value,"+res+",when username="+request.username+",proc_now-1="+request.proc_now,
              run_now: request.run_now,
              hantei: res
            });
            break;
          }
          case "7":{
            var x = document.title;
            console.log(request.tar+" "+ x +" "+request.arc);
            var res = "false";
            if(x==request.arc) res = "true";

            sendResponse({
              msg:"check the title,"+res+",when username="+request.username+",proc_now-1="+request.proc_now,
              run_now: request.run_now,
              hantei: res
            });
            break;
          }
          default:{
            sendResponse({
              msg:"unknown command."+" "+request.run_now,
              run_now: request.run_now
            });
          }

        }
      }

    });

}).call(this);
